refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: rolling_file
    path: "log/sniffer-wall.log"
    append: true
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} {level} {target} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 50 mb
      roller:
        kind: fixed_window
        pattern: 'log/sniffer-wall.log.{}'
        base: 1
        count: 5
root:
  level: info
  appenders:
    - requests